apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2-is-node
  namespace: {{ .Values.Namespace }}
  labels:
    deployment: wso2is # Labels for the deployment itself
spec:
  selector:
    matchLabels:
      deployment: wso2is  # Selector labels to match labels in the pod template
  replicas: {{ .Values.wso2.deployment.wso2is.replicas }}
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 0
  template:
    metadata:
      labels:
        deployment: wso2is  # Labels applied to pods created by this template
    spec:
      containers:
        - name: wso2-is-container
          image: acrasgardeomainrnd001.azurecr.io/is7.0:rc7
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /carbon/admin/login.jsp
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.wso2.deployment.wso2is.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.wso2is.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /api/health-check/v1.0/health
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.wso2.deployment.wso2is.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.wso2is.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 9443
            - containerPort: 4000
            - containerPort: 9763
            - containerPort: 3306
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts: 
            - name: identity-server-conf
              mountPath: /home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
              subPath: deployment.toml
      
      volumes:
        - name: identity-server-conf
{{- if .Values.registry_mode }}
          configMap:
            name: identity-server-conf-ro
{{- else }}
          configMap:
            name: identity-server-conf-rw
{{- end }}
      serviceAccountName: is-service-account